# Generated by Django 4.2.3 on 2023-07-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
        ),
    ]
